### ISSUE TITLE
"Fibers" documentation does not belong under "Continuous Fiber Distribution" in UM

### ISSUE THREAD

**Issue by JeffWeissUT** [febiosoftware/FEBio#21]
The "Fibers" section of the User's Manual (currently 4.2.5) describes fiber constitutive models.  It is currently contained in the subsection 4.2, "Continuous Fiber Distribution".  This is confusing because it implies that the fiber models can only be used with a continuous fiber distribution.  The documentation itself does not provide further clarification.  I think the Fibers subsection should be moved under subsection 4.1, Elastic Solids, and the documentation needs to be updated to clarify that the fiber models can be used without a distribution (but should be used with a matrix term).

**Comment by gateshian** [comment]
The development version of the manual alreay includes descriptions of fibers in Section 4.1.2 Uncoupled Materials (see 4.1.2.5 and 4.1.2.6) and Section 4.1.3 Compressible Materials (see 4.1.3.8 and 4.1.3.9), which explain that fibers are unstable on their own and should be used in a solid mixture.  Historically, fiber materials in continuous fiber distributions (Section 4.2.3) did not share the same class as the standalone fiber materials.  So the material "type" is different, e.g., "fiber-exp-pow" versus "fiber-exponential-power-law" even though these materials now behave the same.  For backward compatibility, we have kept both versions (i.e., those appearing in 4.1.2/4.1.3 and those appearing in 4.2.3).

How do you want to proceed?  We can delete section 4.2.3 (moving 4.2.3.3 to 4.1.3) of the manual but keep the FEBio3 code unchanged for backward compatibility. The User Manual could then state in 4.2.3 that users should pick fiber models such as those in 4.1.2.5, 4.1.2.6, 4.1.3.8 and 4.1.3.9).  This would wean users from the old form. Or we keep things as they are?

**Comment by JeffWeissUT** [comment]
Thanks for pointing me to those sections in the development version. 

I would suggest retitling 4.2 from "Continuous Fiber Distribution" to something like "Fiber Constitutive Models".  Below that, in 4.2.1, list the fiber models first (current section 4.2.3).  Then have a subsection after that, "Continuous Fiber Distributions", under which all material related to CFDs is described.

Then we could delete the subsections describing fiber constitutive models under "Uncoupled Materials" and "Compressible Materials".

**Comment by gateshian** [comment]
I updated the User Manual following your suggestion. However, since the manual only allows four numbered levels for headings (chapter,  section, subsection and subsubsection), I couldn't place the Continuous Fiber Distribution section within the Fibers sections. Please take a look and see if you are satisfied with these changes.

I also took advantage of these edits to clarify two things: (1) Wherever applicable for solid materials, I replaced "compressible" with "unconstrained", to stand in proper contrast with "uncoupled" (which represents a constraint on the volumetric deformation).  I did this primarily because there were sections where we distinguished the fibers as "compressible" vs "uncoupled", even though elsewhere we say that fiber models can only sustain tension, which made the expression "compressible fiber model" seem like an oxymoron. (2) I added a paragraph (now in Section 4.2) which explains that users may optionally combine unconstrained fiber models with uncoupled ground matrix, to overcome some concerns that have been raised in the recent literature about using uncoupled models for fibers (it is all cited in the updated manual).  Please take a look at those changes as well.

**Comment by JeffWeissUT** [comment]
This looks good to me, including the change in terminology, thanks!
