### ISSUE TITLE
FEBio Studio 1.9 does not recognize .feb input files in the repository

### ISSUE THREAD

**Issue by antimonyz** [febiosoftware/FEBio#60]
I am trying to do some multiphasic benchmark test using .feb input files from Repository/Test Suite. However, it tells me "Invalid version for febio_spec" when I open every .feb file in Repository/Test Suite/Multiphasic. Could you advise on how to run the benchmark files in the repository?

**Comment by michaelrossherron** [comment]
All of the files on the repository in the Test Suite category were updated to the latest FEBio 4 specification. This means that if you're trying to open or run the files with FEBio 3.x or FEBio Studio 1.x, then you'll get that error message. 

You'll need to update FEBio and FEBio Studio to the latest version in order to be able to open or run those files. You can find downloads for the latest installers [here](https://febio.org/downloads/). 

I added a message to repository users to inform people of this change, so hopefully this will not cause confusion in the future. 

Let me know if you run into any further issues. Thanks!

Michael Herron

**Comment by antimonyz** [comment]
> All of the files on the repository in the Test Suite category were updated to the latest FEBio 4 specification. This means that if you're trying to open or run the files with FEBio 3.x or FEBio Studio 1.x, then you'll get that error message.
> 
> You'll need to update FEBio and FEBio Studio to the latest version in order to be able to open or run those files. You can find downloads for the latest installers [here](https://febio.org/downloads/).
> 
> I added a message to repository users to inform people of this change, so hopefully this will not cause confusion in the future.
> 
> Let me know if you run into any further issues. Thanks!
> 
> Michael Herron

Hi Mike,

Thanks for your kind reply. I updated FEBio and FEBio Studio to the latest version (FEBio 4.1 & FEBio Studio 2.1.1 on Apr 11, 2023) and successfully tested most of benchmark in Repository/Test Suite/Multiphasic, **EXCEPT mp02.feb** - the same error happened.

Could you solve this issue?

Best,

Shubo

**Comment by michaelrossherron** [comment]
Shubo,

I'm unable to replicate the issue with mp02.feb. I can open the file in FEBio Studio, and run it with FEBio without any problems. 

Perhaps there's something wrong with your local copy of that file. By default, the repository will not redownload files that you already have downloaded, even if you've modified them locally. If you open the repository again, and then right click on mp02.feb, and select Download from the menu, it will download a new copy from the repository, overwriting any local changes you may have.

If you're still having trouble opening that file then perhaps give me some more details about what exactly you're trying to do with the file so that I can try to replicate the issue. 

Michael Herron

**Comment by antimonyz** [comment]
Thanks for your help! I can run it after re-download.
