### ISSUE TITLE
Some questoin about body load 

### ISSUE THREAD

**Issue by CaiweiWekonh** [febiosoftware/FEBio#68]
Hi Steve!
I'm using FEBio(2.2.0) to do some computational work about solid mechanics and feel confused about the "body load" module. There is  a kind of body load namede 'point' with three parameters <a> <b> and <rc> but I can't find  the meaning of these 3 parameters on FEBio User Manual.
Maybe you can tell me the meaning of the 3 parameters or where to find the information about this?
Thank you,
Wekonh.

**Comment by gateshian** [comment]
Hi Wekonh,

Indeed it seems that this body force is not documented (so it was probably added as an experimental feature but didn't deserve to be released).  Since FEBioStudio 2 now taps into the FEBio libraries directly, it finds all the old features that were introduced as experimental features and makes them visible to all users, even if they weren't documented.  It seems this old implementation of a "Point" body force falls under this category.

Basically, looking at the source code, one can deduce that this body force applies at a single point, either a user-specified point via the vector parameter "rc", or via the "node" number.  The magnitude of the force is exponential, decaying from the center to any location inside the body via the exponential function a*exp(-b*d), where "a" and "b" are user-defined parameters and "d" is the distance of any point in the body to the center point. The "rigid" flag indicates if the center point is located inside a rigid body (or not).

I hope that helps.  Since this type of body force is not particularly useful to the general public, we don't plan to document it and will probably hide it from view in future releases.

Best,

Gerard

**Comment by CaiweiWekonh** [comment]
@gateshian Oh! Thanks for your answer! It helps. Thank you very much!
