### ISSUE TITLE
Request for FEBioBinaryDatabaseSpecification for Spec 4.0

### ISSUE THREAD

**Issue by Nobregaigor** [febiosoftware/FEBio#90]
Hi FEBio Developers,

I am currently developing a FEBio-Python package that enables users to create and manipulate FEBio input files directly from Python. This functionality supports the creation of custom and complex parametric simulations, as well as the direct reading and post-processing of xplt results within Python. You can find the full documentation for this package here: [FEBio-Python GitHub Repository](https://github.com/Nobregaigor/febio-python).

I am in the process of updating both the FEB and XPLT writers/readers in my package from spec 3.0 to spec 4.0. However, I've encountered an issue: **the new download version does not include the updated documentation for spec 4.0.**

Could you please provide guidance on **where I can find the new FEBioBinaryDatabaseSpecification for spec 4.0**? If it is possible to share the updated specification, it would greatly facilitate the update process for my package.

Thank you for your assistance and for your continued work on FEBio!

**Comment by michaelrossherron** [comment]
The FEBio Binary Database Specification is no longer distributed as its own document. You can now find it in Appendix D of the FEBio User Manual. This appendix still describes version 3.0 fo the format, but there have been very few changes since this documentation was made. Unfortunately, we haven't yet created updated documentation, but this should work for almost everything you need. If you are running into issues with specific parts of any xplt file, please let us know, and we can help you with that. 

Michael Herron

**Comment by SteveMaas1978** [comment]
Just to clarify, there is no version 4 of the xplt specification and there are no current plans to make a new specification. Both FEBio and FEBio Studio still use the 3.x specification. Given that, I don't see a real issue here, so closing this. 
If you are running into issues with reading plot files, feel free to open a new issue. 

Best,

Steve

**Comment by Nobregaigor** [comment]
Thank you for the clarification!
